import type { Listing } from '$lib/types/listing';

// Placeholder images from picsum — deterministic by ID so they're stable
const img = (id: number, w = 800, h = 500) => `https://picsum.photos/seed/car${id}/${w}/${h}`;

export const mockListings: Listing[] = [
	{
		id: 'lst-001',
		title: '2019 Honda CR-V EX-L AWD',
		year: 2019,
		make: 'Honda',
		model: 'CR-V',
		trim: 'EX-L',
		price: 22_500,
		marketAverage: 24_800,
		priceBadge: 'below_market',
		mileage: 41_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Lunar Silver Metallic',
		vin: '2HKRW2H8****4521',
		description:
			'One owner, garage kept, non-smoker. Full Honda dealer service history — all oil changes, brake service, and the 40k major service done at Honda of Scarborough. Heated front seats, sunroof, Apple CarPlay. No accidents on Carfax. Winter tires included on separate rims. Selling because we bought a minivan.',
		photos: [img(1), img(2), img(3), img(4)],
		location: 'Toronto, ON',
		seller: {
			username: 'PaulaT_Drives',
			feedbackScore: 312,
			feedbackPercent: 99.4,
			location: 'Toronto, ON',
			memberSince: '2014-03-11',
			type: 'private'
		},
		watcherCount: 47,
		saveCount: 23,
		listedAt: '2026-03-28'
	},
	{
		id: 'lst-002',
		title: '2021 Toyota RAV4 XLE Premium',
		year: 2021,
		make: 'Toyota',
		model: 'RAV4',
		trim: 'XLE Premium',
		price: 31_900,
		marketAverage: 30_400,
		priceBadge: 'above_market',
		mileage: 28_500,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Blueprint',
		vin: '2T3P1RFV****8802',
		description:
			'Certified Pre-Owned. 160-point inspection completed. Toyota Certified warranty until 2027. Includes all weather mats, cargo tray, and block heater. Full dealer service records available. Available for test drive at our Mississauga location.',
		photos: [img(5), img(6), img(7), img(8)],
		location: 'Mississauga, ON',
		seller: {
			username: 'OakvilleToyota_Official',
			feedbackScore: 2841,
			feedbackPercent: 98.7,
			location: 'Mississauga, ON',
			memberSince: '2009-06-02',
			type: 'dealer'
		},
		watcherCount: 62,
		saveCount: 31,
		listedAt: '2026-03-27'
	},
	{
		id: 'lst-003',
		title: '2017 Ford F-150 XLT SuperCrew 4x4',
		year: 2017,
		make: 'Ford',
		model: 'F-150',
		trim: 'XLT',
		price: 24_800,
		marketAverage: 24_200,
		priceBadge: 'fair',
		mileage: 87_400,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Oxford White',
		vin: '1FTFW1EF****3317',
		description:
			'Good condition overall. Some light scratches on the tailgate — photos included. 3.5L EcoBoost. Tows well, used for light hauling. Service records from 2017-2022 available, then moved to an independent shop. New rear brakes at 80k. Tires at 60%.',
		photos: [img(9), img(10), img(11)],
		location: 'Calgary, AB',
		seller: {
			username: 'mike_alberta',
			feedbackScore: 89,
			feedbackPercent: 97.8,
			location: 'Calgary, AB',
			memberSince: '2017-08-14',
			type: 'private'
		},
		watcherCount: 38,
		saveCount: 15,
		listedAt: '2026-03-25'
	},
	{
		id: 'lst-004',
		title: '2022 Mazda CX-5 GT AWD',
		year: 2022,
		make: 'Mazda',
		model: 'CX-5',
		trim: 'GT',
		price: 33_500,
		marketAverage: 35_100,
		priceBadge: 'below_market',
		mileage: 19_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Soul Red Crystal',
		vin: 'JM3KFBDM****5573',
		description:
			'Company vehicle — meticulously maintained by our fleet service department. Full Mazda dealer service history. No accidents, no rentals. Interior like new. Includes the GT-exclusive Bose audio, heated/ventilated seats, HUD. Transferable balance of Mazda factory warranty.',
		photos: [img(12), img(13), img(14), img(15), img(16)],
		location: 'Vancouver, BC',
		seller: {
			username: 'PacificFleetSales',
			feedbackScore: 1204,
			feedbackPercent: 99.1,
			location: 'Vancouver, BC',
			memberSince: '2011-01-20',
			type: 'dealer'
		},
		watcherCount: 71,
		saveCount: 44,
		listedAt: '2026-03-29'
	},
	{
		id: 'lst-005',
		title: '2015 Toyota Camry XSE V6',
		year: 2015,
		make: 'Toyota',
		model: 'Camry',
		trim: 'XSE V6',
		price: 13_200,
		marketAverage: 14_800,
		priceBadge: 'below_market',
		mileage: 118_000,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'fwd',
		color: 'Midnight Black Metallic',
		vin: '4T1BK1FK****6605',
		description: 'High mileage but runs great. V6 has plenty of power.',
		photos: [img(17), img(18)],
		location: 'Ottawa, ON',
		seller: {
			username: 'dave_ottawa99',
			feedbackScore: 44,
			feedbackPercent: 96.2,
			location: 'Ottawa, ON',
			memberSince: '2019-11-30',
			type: 'private'
		},
		watcherCount: 22,
		saveCount: 9,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-006',
		title: '2020 Volkswagen Golf GTI Autobahn',
		year: 2020,
		make: 'Volkswagen',
		model: 'Golf GTI',
		trim: 'Autobahn',
		price: 27_900,
		marketAverage: 26_500,
		priceBadge: 'above_market',
		mileage: 33_100,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Tornado Red',
		vin: '3VW547AUXLM****42',
		description:
			'6-speed manual, never tracked. Full VW dealer service records. DCC adaptive suspension. Heated seats, 8" Discover Pro nav. Continental ExtremeContact Sport tires new at 28k. One minor paint chip on hood — retouched. Available for inspection at our facility in Oakville.',
		photos: [img(19), img(20), img(21), img(22)],
		location: 'Oakville, ON',
		seller: {
			username: 'PrestigeAutoHaus',
			feedbackScore: 743,
			feedbackPercent: 98.9,
			location: 'Oakville, ON',
			memberSince: '2013-05-17',
			type: 'dealer'
		},
		watcherCount: 58,
		saveCount: 27,
		listedAt: '2026-03-26'
	},
	{
		id: 'lst-007',
		title: '2016 Honda Civic LX Sedan',
		year: 2016,
		make: 'Honda',
		model: 'Civic',
		trim: 'LX',
		price: 9_400,
		marketAverage: 10_200,
		priceBadge: 'below_market',
		mileage: 134_500,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Taffeta White',
		vin: '2HGFC2F5****7801',
		description: 'Reliable daily. Good condition.',
		photos: [img(23), img(24)],
		location: 'Hamilton, ON',
		seller: {
			username: 'sam_h_sells',
			feedbackScore: 28,
			feedbackPercent: 100,
			location: 'Hamilton, ON',
			memberSince: '2021-02-08',
			type: 'private'
		},
		watcherCount: 19,
		saveCount: 6,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-008',
		title: '2023 Subaru Outback Touring XT',
		year: 2023,
		make: 'Subaru',
		model: 'Outback',
		trim: 'Touring XT',
		price: 41_500,
		marketAverage: 42_800,
		priceBadge: 'below_market',
		mileage: 11_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Autumn Green Metallic',
		vin: '4S4BTAPC****3302',
		description:
			'Nearly new. Lease return off a 24-month corporate lease. Full Subaru CPO inspection and recertification completed. Factory warranty in full effect until 2027 / 80,000 km. Starlink telematics subscription current. All-season mats, splash guards, dog guard included.',
		photos: [img(25), img(26), img(27), img(28)],
		location: 'Edmonton, AB',
		seller: {
			username: 'NorthStarSubaru',
			feedbackScore: 1893,
			feedbackPercent: 99.3,
			location: 'Edmonton, AB',
			memberSince: '2008-09-14',
			type: 'dealer'
		},
		watcherCount: 84,
		saveCount: 52,
		listedAt: '2026-03-31'
	},
	{
		id: 'lst-009',
		title: '2018 BMW 330i xDrive',
		year: 2018,
		make: 'BMW',
		model: '3 Series',
		trim: '330i xDrive',
		price: 26_800,
		marketAverage: 28_900,
		priceBadge: 'below_market',
		mileage: 68_400,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Melbourne Red',
		vin: 'WBA8B9C5****2261',
		description:
			'Sport Line package. Heads-up display, harman/kardon audio. Recent service: oil and filter at 66k, new front tires at 64k. Some curb rash on rear left wheel — see photos. Timing chain recall completed at BMW dealer. Maintenance records available.',
		photos: [img(29), img(30), img(31), img(32)],
		location: 'Toronto, ON',
		seller: {
			username: 'euro_drives_toronto',
			feedbackScore: 156,
			feedbackPercent: 98.1,
			location: 'Toronto, ON',
			memberSince: '2016-07-22',
			type: 'private'
		},
		watcherCount: 43,
		saveCount: 18,
		listedAt: '2026-03-28'
	},
	{
		id: 'lst-010',
		title: '2014 Chevrolet Silverado 1500 LTZ',
		year: 2014,
		make: 'Chevrolet',
		model: 'Silverado 1500',
		trim: 'LTZ',
		price: 18_500,
		marketAverage: 17_800,
		priceBadge: 'fair',
		mileage: 156_200,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Tungsten Metallic',
		vin: '1GCVKREC****4432',
		description:
			'High mileage, priced to move. 5.3L V8. Z71 off-road package. New transmission at 140k (receipt included). Good rubber. Some surface rust on underside — normal for a Saskatchewan truck. Everything works.',
		photos: [img(33), img(34), img(35)],
		location: 'Saskatoon, SK',
		seller: {
			username: 'prairie_fleet_sk',
			feedbackScore: 67,
			feedbackPercent: 97.0,
			location: 'Saskatoon, SK',
			memberSince: '2018-04-03',
			type: 'private'
		},
		watcherCount: 31,
		saveCount: 12,
		listedAt: '2026-03-24'
	},
	{
		id: 'lst-011',
		title: '2021 Hyundai Tucson Preferred AWD',
		year: 2021,
		make: 'Hyundai',
		model: 'Tucson',
		trim: 'Preferred',
		price: 24_900,
		marketAverage: 25_600,
		priceBadge: 'below_market',
		mileage: 38_700,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Phantom Black',
		vin: 'KM8J2CA4****9012',
		description:
			'One owner, accident free. Full Hyundai dealer service history. Remote start, heated seats/wheel, blind spot monitoring. Winter tires (stored separately) included. Non-smoker, no pets. Moving abroad — must sell.',
		photos: [img(36), img(37), img(38), img(39)],
		location: 'Montréal, QC',
		seller: {
			username: 'leila_mtl',
			feedbackScore: 74,
			feedbackPercent: 100,
			location: 'Montréal, QC',
			memberSince: '2020-01-15',
			type: 'private'
		},
		watcherCount: 53,
		saveCount: 29,
		listedAt: '2026-03-29'
	},
	{
		id: 'lst-012',
		title: '2019 Audi Q5 Progressiv Quattro',
		year: 2019,
		make: 'Audi',
		model: 'Q5',
		trim: 'Progressiv',
		price: 34_700,
		marketAverage: 32_900,
		priceBadge: 'above_market',
		mileage: 52_300,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Floret Silver',
		vin: 'WA1BNAFY****3344',
		description:
			'Virtual Cockpit, panoramic sunroof, massage seats. Serviced exclusively at Audi Centre Ottawa — full records. Extended Audi Care prepaid maintenance plan transferable to new owner (covers next 2 services). New Continental tires at 48k.',
		photos: [img(40), img(41), img(42), img(43)],
		location: 'Ottawa, ON',
		seller: {
			username: 'AudiCentreOttawa',
			feedbackScore: 3102,
			feedbackPercent: 99.0,
			location: 'Ottawa, ON',
			memberSince: '2007-03-12',
			type: 'dealer'
		},
		watcherCount: 67,
		saveCount: 35,
		listedAt: '2026-03-27'
	},
	{
		id: 'lst-013',
		title: '2020 Kia Telluride EX AWD',
		year: 2020,
		make: 'Kia',
		model: 'Telluride',
		trim: 'EX',
		price: 35_500,
		marketAverage: 36_200,
		priceBadge: 'fair',
		mileage: 44_100,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Snow White Pearl',
		vin: '5XYP3DHC****1177',
		description:
			'8-seat configuration. Fully loaded EX: panoramic sunroof, second-row captain chairs, 10.25" touchscreen. Kia dealer service records complete. Tires replaced at 40k. Child seat anchors in all 3 rows. Perfect family SUV.',
		photos: [img(44), img(45), img(46), img(47)],
		location: 'Winnipeg, MB',
		seller: {
			username: 'KiaCityWinnipeg',
			feedbackScore: 988,
			feedbackPercent: 98.5,
			location: 'Winnipeg, MB',
			memberSince: '2010-08-22',
			type: 'dealer'
		},
		watcherCount: 76,
		saveCount: 41,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-014',
		title: '2012 Toyota Prius Three',
		year: 2012,
		make: 'Toyota',
		model: 'Prius',
		trim: 'Three',
		price: 7_900,
		marketAverage: 9_100,
		priceBadge: 'below_market',
		mileage: 189_000,
		mileageBadge: 'high',
		condition: 'fair',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Classic Silver Metallic',
		vin: 'JTDKN3DU****8811',
		description: 'High mileage. Still gets 5L/100km. Some cosmetic wear.',
		photos: [img(48), img(49)],
		location: 'Victoria, BC',
		seller: {
			username: 'vic_green_cars',
			feedbackScore: 19,
			feedbackPercent: 94.7,
			location: 'Victoria, BC',
			memberSince: '2022-06-10',
			type: 'private'
		},
		watcherCount: 14,
		saveCount: 4,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-015',
		title: '2023 Tesla Model Y Long Range AWD',
		year: 2023,
		make: 'Tesla',
		model: 'Model Y',
		trim: 'Long Range',
		price: 52_900,
		marketAverage: 55_400,
		priceBadge: 'below_market',
		mileage: 16_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Pearl White Multi-Coat',
		vin: '5YJYGDEE****1102',
		description:
			'20" Induction wheels. Full Self-Driving (Supervised) capability included. Wall Connector and mobile connector included. Tesla app history available. No accidents. Supercharger credit balance transferable. Only selling due to company lease allowance change.',
		photos: [img(50), img(51), img(52), img(53)],
		location: 'Calgary, AB',
		seller: {
			username: 'ryan_ev_yeg',
			feedbackScore: 203,
			feedbackPercent: 99.5,
			location: 'Calgary, AB',
			memberSince: '2015-11-04',
			type: 'private'
		},
		watcherCount: 93,
		saveCount: 61,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-016',
		title: '2018 Ram 1500 Laramie Crew Cab 4x4',
		year: 2018,
		make: 'Ram',
		model: '1500',
		trim: 'Laramie',
		price: 36_400,
		marketAverage: 33_800,
		priceBadge: 'above_market',
		mileage: 71_200,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Bright Silver Metallic',
		vin: '1C6RR7NT****5522',
		description:
			'Fully loaded Laramie: RamBox bed storage, Level 2 equipment group, 12" Uconnect 4C nav, heated/cooled leather, panoramic sunroof. Air suspension. All stock, no lifts or mods. Full Ram dealer service records. Always garaged.',
		photos: [img(54), img(55), img(56), img(57)],
		location: 'London, ON',
		seller: {
			username: 'StarlightAutoLondon',
			feedbackScore: 512,
			feedbackPercent: 97.8,
			location: 'London, ON',
			memberSince: '2012-02-14',
			type: 'dealer'
		},
		watcherCount: 49,
		saveCount: 21,
		listedAt: '2026-03-26'
	},
	{
		id: 'lst-017',
		title: '2016 Jeep Cherokee Trailhawk 4x4',
		year: 2016,
		make: 'Jeep',
		model: 'Cherokee',
		trim: 'Trailhawk',
		price: 15_800,
		marketAverage: 15_400,
		priceBadge: 'fair',
		mileage: 103_400,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Hydro Blue Pearl',
		vin: '1C4PJMBS****7733',
		description:
			'9-speed automatic (recently relearned at dealer). Selec-Terrain 4x4. Rock Rails and Skid plates stock. Some rock chips on front bumper — expected for a Trailhawk. ZF recall completed. Recent: new battery, air filter.',
		photos: [img(58), img(59), img(60)],
		location: 'Halifax, NS',
		seller: {
			username: 'jason_ns_offroad',
			feedbackScore: 52,
			feedbackPercent: 98.1,
			location: 'Halifax, NS',
			memberSince: '2019-03-28',
			type: 'private'
		},
		watcherCount: 27,
		saveCount: 11,
		listedAt: '2026-03-27'
	},
	{
		id: 'lst-018',
		title: '2022 Ford Bronco Outer Banks 4-Door',
		year: 2022,
		make: 'Ford',
		model: 'Bronco',
		trim: 'Outer Banks',
		price: 54_900,
		marketAverage: 51_200,
		priceBadge: 'above_market',
		mileage: 22_700,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Eruption Green',
		vin: '1FMEE5DP****4401',
		description:
			'Sasquatch Package. Mid package soft-top. Modular bumpers stock. Never taken off-road. Hard top doors and panels stored and included. MIC hardtop ordered from Ford dealer but NOT included (allocated separately). No accidents. Priced at market premium for colour scarcity.',
		photos: [img(61), img(62), img(63), img(64)],
		location: 'Vancouver, BC',
		seller: {
			username: 'west_coast_rigs',
			feedbackScore: 181,
			feedbackPercent: 99.2,
			location: 'Vancouver, BC',
			memberSince: '2014-09-05',
			type: 'private'
		},
		watcherCount: 88,
		saveCount: 57,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-019',
		title: '2013 Honda Accord Sport Sedan',
		year: 2013,
		make: 'Honda',
		model: 'Accord',
		trim: 'Sport',
		price: 8_200,
		marketAverage: 9_700,
		priceBadge: 'below_market',
		mileage: 144_800,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Alabaster Silver',
		vin: '1HGCR2F5****9941',
		description: 'Clean title. Manual trans shifts cleanly. Good.',
		photos: [img(65), img(66)],
		location: 'Kitchener, ON',
		seller: {
			username: 'kitchener_cars',
			feedbackScore: 37,
			feedbackPercent: 97.3,
			location: 'Kitchener, ON',
			memberSince: '2020-07-19',
			type: 'private'
		},
		watcherCount: 16,
		saveCount: 7,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-020',
		title: '2021 Genesis GV80 3.5T AWD',
		year: 2021,
		make: 'Genesis',
		model: 'GV80',
		trim: '3.5T AWD',
		price: 59_800,
		marketAverage: 61_400,
		priceBadge: 'below_market',
		mileage: 24_300,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Havana Brown',
		vin: 'KMUHBDSB****8821',
		description:
			'Prestige Package. 3.5T twin-turbo V6, air suspension. Head-up display, rear entertainment, 14-speaker Lexicon audio, 7-passenger configuration. Remote Smart Parking Assist. Valet mode logged. Full Genesis dealer service history. One of the most complete feature sets in this class at this price.',
		photos: [img(67), img(68), img(69), img(70)],
		location: 'Toronto, ON',
		seller: {
			username: 'GenesisOfNorthYork',
			feedbackScore: 2241,
			feedbackPercent: 99.6,
			location: 'Toronto, ON',
			memberSince: '2018-05-01',
			type: 'dealer'
		},
		watcherCount: 79,
		saveCount: 48,
		listedAt: '2026-03-31'
	}
];
