import type { Listing } from '$lib/types/listing';

const repeatPhoto = (url: string, count: number) => Array.from({ length: count }, () => url);

export const mockListings: Listing[] = [
	{
		id: 'lst-001',
		title: '2019 Honda CR-V EX-L AWD',
		year: 2019,
		make: 'Honda',
		model: 'CR-V',
		trim: 'EX-L',
		price: 22_900,
		marketAverage: 24_700,
		priceBadge: 'below_market',
		mileage: 46_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Lunar Silver Metallic',
		vin: '2HKRW2H8****4521',
		description:
			'One-owner family SUV with Honda dealer records from new. EX-L trim with leather, heated seats, power tailgate, sunroof, and Apple CarPlay. Recent work includes rear brakes, battery, and the 48k service. No accident claims reported. Includes winter wheels and cargo tray.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/2019_Honda_CR-V_1.5_TC_2WD_%285%29.jpg/960px-2019_Honda_CR-V_1.5_TC_2WD_%285%29.jpg',
			4
		),
		location: 'Toronto, ON',
		seller: {
			username: 'PaulaT_Drives',
			feedbackScore: 318,
			feedbackPercent: 99.4,
			location: 'Toronto, ON',
			memberSince: '2014-03-11',
			type: 'private'
		},
		watcherCount: 52,
		saveCount: 27,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-002',
		title: '2021 Toyota RAV4 XLE Premium AWD',
		year: 2021,
		make: 'Toyota',
		model: 'RAV4',
		trim: 'XLE Premium',
		price: 31_800,
		marketAverage: 30_900,
		priceBadge: 'above_market',
		mileage: 29_400,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Blueprint',
		vin: '2T3P1RFV****8802',
		description:
			'Toyota Certified with balance of powertrain warranty and a fresh 160-point inspection. XLE Premium with SofTex, power liftgate, sunroof, blind-spot monitoring, and all-weather liners. Dealer asking a premium because it is clean, local, and fully reconditioned.',
		photos: repeatPhoto('/listings/lst-002.jpg', 4),
		location: 'Mississauga, ON',
		seller: {
			username: 'OakvilleToyota_Official',
			feedbackScore: 2841,
			feedbackPercent: 98.7,
			location: 'Mississauga, ON',
			memberSince: '2009-06-02',
			type: 'dealer'
		},
		watcherCount: 64,
		saveCount: 35,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-003',
		title: '2017 Ford F-150 XLT SuperCrew 4x4',
		year: 2017,
		make: 'Ford',
		model: 'F-150',
		trim: 'XLT',
		price: 24_600,
		marketAverage: 24_100,
		priceBadge: 'fair',
		mileage: 89_700,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Oxford White',
		vin: '1FTFW1EF****3317',
		description:
			'3.5L EcoBoost, SuperCrew, tow package, spray-in liner. Used for commuting and weekend hardware-store runs, not heavy towing. Service history is complete to 2022, then maintained at a local independent shop. Tailgate and rear bumper have light scratches shown in photos.',
		photos: repeatPhoto('/listings/lst-003.jpg', 4),
		location: 'Calgary, AB',
		seller: {
			username: 'mike_alberta',
			feedbackScore: 91,
			feedbackPercent: 97.8,
			location: 'Calgary, AB',
			memberSince: '2017-08-14',
			type: 'private'
		},
		watcherCount: 37,
		saveCount: 15,
		listedAt: '2026-03-28'
	},
	{
		id: 'lst-004',
		title: '2022 Mazda CX-5 GT AWD',
		year: 2022,
		make: 'Mazda',
		model: 'CX-5',
		trim: 'GT',
		price: 33_400,
		marketAverage: 35_000,
		priceBadge: 'below_market',
		mileage: 22_100,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Soul Red Crystal',
		vin: 'JM3KFBDM****5573',
		description:
			'Former executive fleet vehicle with complete Mazda dealer history and recent inspection. GT trim includes Bose audio, HUD, heated and ventilated front seats, heated rear seats, adaptive cruise, and power tailgate. Very clean interior, no smoke smell, no visible wear on bolsters.',
		photos: repeatPhoto('/listings/lst-004.jpg', 5),
		location: 'Vancouver, BC',
		seller: {
			username: 'PacificFleetSales',
			feedbackScore: 1204,
			feedbackPercent: 99.1,
			location: 'Vancouver, BC',
			memberSince: '2011-01-20',
			type: 'dealer'
		},
		watcherCount: 73,
		saveCount: 46,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-005',
		title: '2015 Toyota Camry XSE V6',
		year: 2015,
		make: 'Toyota',
		model: 'Camry',
		trim: 'XSE V6',
		price: 13_100,
		marketAverage: 14_900,
		priceBadge: 'below_market',
		mileage: 121_400,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'fwd',
		color: 'Midnight Black Metallic',
		vin: '4T1BK1FK****6605',
		description:
			'High-mileage V6 Camry that still drives strong. Two keys, remote start, and recent front struts. Seller says there is no rust through, only stone chips and a crack in the lower front lip. Description is brief, so a buyer should confirm oil-consumption history and transmission service.',
		photos: repeatPhoto('/listings/lst-005.jpg', 3),
		location: 'Ottawa, ON',
		seller: {
			username: 'dave_ottawa99',
			feedbackScore: 44,
			feedbackPercent: 96.2,
			location: 'Ottawa, ON',
			memberSince: '2019-11-30',
			type: 'private'
		},
		watcherCount: 24,
		saveCount: 10,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-006',
		title: '2020 Volkswagen Golf GTI Autobahn 6MT',
		year: 2020,
		make: 'Volkswagen',
		model: 'Golf GTI',
		trim: 'Autobahn',
		price: 28_100,
		marketAverage: 26_800,
		priceBadge: 'above_market',
		mileage: 34_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Tornado Red',
		vin: '3VW547AUXLM****42',
		description:
			'Manual Autobahn with DCC, Fender audio, navigation, and plaid-seat delete. Seller states the car was never tracked and remains stock aside from Michelin Pilot Sport tires. Dealer reconditioning included fresh front brakes and a carbon cleaning service. Strong enthusiast appeal, but priced above average.',
		photos: repeatPhoto('/listings/lst-006.jpg', 4),
		location: 'Oakville, ON',
		seller: {
			username: 'PrestigeAutoHaus',
			feedbackScore: 743,
			feedbackPercent: 98.9,
			location: 'Oakville, ON',
			memberSince: '2013-05-17',
			type: 'dealer'
		},
		watcherCount: 59,
		saveCount: 30,
		listedAt: '2026-03-29'
	},
	{
		id: 'lst-007',
		title: '2016 Honda Civic LX Sedan',
		year: 2016,
		make: 'Honda',
		model: 'Civic',
		trim: 'LX',
		price: 9_200,
		marketAverage: 10_300,
		priceBadge: 'below_market',
		mileage: 136_900,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Taffeta White',
		vin: '2HGFC2F5****7801',
		description: 'Reliable commuter. Good on gas. Two sets of tires. Selling as-is.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/2016_Honda_Civic_EX-T_in_Modern_Steel_Metallic%2C_front_left%2C_04-26-2025.jpg/960px-2016_Honda_Civic_EX-T_in_Modern_Steel_Metallic%2C_front_left%2C_04-26-2025.jpg',
			2
		),
		location: 'Hamilton, ON',
		seller: {
			username: 'sam_h_sells',
			feedbackScore: 28,
			feedbackPercent: 100,
			location: 'Hamilton, ON',
			memberSince: '2021-02-08',
			type: 'private'
		},
		watcherCount: 21,
		saveCount: 8,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-008',
		title: '2023 Subaru Outback Touring XT',
		year: 2023,
		make: 'Subaru',
		model: 'Outback',
		trim: 'Touring XT',
		price: 41_200,
		marketAverage: 42_900,
		priceBadge: 'below_market',
		mileage: 12_600,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Autumn Green Metallic',
		vin: '4S4BTAPC****3302',
		description:
			'Turbo Touring XT lease return with the full Subaru Eyesight suite, Nappa leather, heated wheel, ventilated seats, front camera, and factory hitch. Dealer notes a clean inspection and original paint on all panels. Strong fit for family-road-trip and winter-weather searches.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/2023_Subaru_Outback_Premium%2C_front_right%2C_09-09-2023.jpg/960px-2023_Subaru_Outback_Premium%2C_front_right%2C_09-09-2023.jpg',
			4
		),
		location: 'Edmonton, AB',
		seller: {
			username: 'NorthStarSubaru',
			feedbackScore: 1893,
			feedbackPercent: 99.3,
			location: 'Edmonton, AB',
			memberSince: '2008-09-14',
			type: 'dealer'
		},
		watcherCount: 86,
		saveCount: 54,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-009',
		title: '2007 Porsche 911 Carrera S Coupe 6MT',
		year: 2007,
		make: 'Porsche',
		model: '911',
		trim: 'Carrera S',
		price: 63_900,
		marketAverage: 66_800,
		priceBadge: 'below_market',
		mileage: 88_400,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Basalt Black Metallic',
		vin: 'WP0AB299****1884',
		description:
			'997.1 Carrera S six-speed with Sport Chrono, PASM, heated adaptive seats, and a documented clutch plus IMS retrofit completed by an independent Porsche specialist at 72k km. Paint-meter photos and recent compression numbers are included. Clean driver-quality 911 with enough provenance to interest collectors, but buyers will still want a specialist PPI.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/c/c4/Porsche_997_Turbo_-_Flickr_-_Alexandre_Pr%C3%A9vot_%288%29.jpg',
			4
		),
		location: 'Montreal, QC',
		seller: {
			username: 'flat6_collection',
			feedbackScore: 211,
			feedbackPercent: 99.1,
			location: 'Montreal, QC',
			memberSince: '2015-04-19',
			type: 'private'
		},
		watcherCount: 97,
		saveCount: 61,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-010',
		title: '1967 Ford Mustang Fastback 289 Project',
		year: 1967,
		make: 'Ford',
		model: 'Mustang',
		trim: 'Fastback 289',
		price: 29_500,
		marketAverage: 34_200,
		priceBadge: 'below_market',
		mileage: 12_000,
		mileageBadge: 'average',
		condition: 'fair',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Primer Grey',
		vin: '7R02C****1542',
		description:
			'Rolling restoration candidate with rebuilt 289 on a stand, Toploader four-speed, and many interior trim pieces boxed in the trunk. Seller says the car is largely complete but still needs wiring, glass seals, and final bodywork before paint. Floors were patched years ago and there is no Marti report on file yet, so this is the right kind of vintage listing for a project-minded buyer, not someone expecting turnkey quality.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/7/7f/1965_Ford_Mustang_2D_Hardtop_Front.jpg',
			3
		),
		location: 'Regina, SK',
		seller: {
			username: 'prairie_fastback_parts',
			feedbackScore: 58,
			feedbackPercent: 96.4,
			location: 'Regina, SK',
			memberSince: '2018-09-11',
			type: 'private'
		},
		watcherCount: 88,
		saveCount: 64,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-011',
		title: '2021 Hyundai Tucson Preferred AWD',
		year: 2021,
		make: 'Hyundai',
		model: 'Tucson',
		trim: 'Preferred',
		price: 24_700,
		marketAverage: 25_800,
		priceBadge: 'below_market',
		mileage: 40_500,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Phantom Black',
		vin: 'KM8J2CA4****9012',
		description:
			'One-owner Tucson with heated seats, heated wheel, lane keep assist, blind-spot monitoring, and remote start. Seller is moving overseas and wants a quick sale but still has dealer maintenance invoices. Good example of a realistic private listing that is clean, credible, and slightly under market.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/2021_Hyundai_Tucson_Elite_N-Line_front_%281%29.jpg/960px-2021_Hyundai_Tucson_Elite_N-Line_front_%281%29.jpg',
			4
		),
		location: 'Montreal, QC',
		seller: {
			username: 'leila_mtl',
			feedbackScore: 74,
			feedbackPercent: 100,
			location: 'Montreal, QC',
			memberSince: '2020-01-15',
			type: 'private'
		},
		watcherCount: 55,
		saveCount: 30,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-012',
		title: '2012 Nissan GT-R Premium',
		year: 2012,
		make: 'Nissan',
		model: 'GT-R',
		trim: 'Premium',
		price: 96_500,
		marketAverage: 92_300,
		priceBadge: 'above_market',
		mileage: 41_900,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Gun Metallic',
		vin: 'JN1AR5EF****4093',
		description:
			'Premium GT-R with Cobb accessport, Midori titanium cat-back, and transmission service documented at a GT-R specialist 3,000 km ago. Seller states the car has not been launched on drag radials and includes stock exhaust plus dyno sheet. High-end enthusiast listing with strong mods and records, but the premium ask only works if buyers trust the maintenance story.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/NISSAN_GT-R_R35_2011.JPG/960px-NISSAN_GT-R_R35_2011.JPG',
			4
		),
		location: 'Calgary, AB',
		seller: {
			username: 'yyc_boost_club',
			feedbackScore: 147,
			feedbackPercent: 98.8,
			location: 'Calgary, AB',
			memberSince: '2014-07-08',
			type: 'private'
		},
		watcherCount: 118,
		saveCount: 83,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-013',
		title: '1989 BMW 325is Coupe 5-Speed',
		year: 1989,
		make: 'BMW',
		model: '325is',
		trim: 'Coupe',
		price: 21_900,
		marketAverage: 22_100,
		priceBadge: 'fair',
		mileage: 214_300,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Alpine White II',
		vin: 'WBAAA130****6128',
		description:
			'Mostly stock E30 coupe with original sport seats, basketweaves, and a thick binder of service receipts going back to 2006. Seller discloses bubbling on the left rear arch, a cracked dash, and older repaint work on the hood. Strong vintage driver-grade car for the money, but originality, rust, and deferred cosmetic work all matter here.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/E30_coupe_M_Technic_PL.JPG/960px-E30_coupe_M_Technic_PL.JPG',
			4
		),
		location: 'Victoria, BC',
		seller: {
			username: 'island_classics',
			feedbackScore: 93,
			feedbackPercent: 99.0,
			location: 'Victoria, BC',
			memberSince: '2016-02-27',
			type: 'private'
		},
		watcherCount: 84,
		saveCount: 49,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-014',
		title: '2012 Toyota Prius Three',
		year: 2012,
		make: 'Toyota',
		model: 'Prius',
		trim: 'Three',
		price: 7_800,
		marketAverage: 9_000,
		priceBadge: 'below_market',
		mileage: 191_600,
		mileageBadge: 'high',
		condition: 'fair',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Classic Silver Metallic',
		vin: 'JTDKN3DU****8811',
		description:
			'High-mileage commuter with cosmetic wear, a cracked rear bumper corner, and fading on the roof. Seller says the hybrid battery is original and the car still returns strong fuel economy. This is intentionally a riskier budget listing that should trigger battery-health and maintenance questions.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/2012_Toyota_Prius_v_Five%2C_front_left%2C_06-13-2023.jpg/960px-2012_Toyota_Prius_v_Five%2C_front_left%2C_06-13-2023.jpg',
			3
		),
		location: 'Victoria, BC',
		seller: {
			username: 'vic_green_cars',
			feedbackScore: 19,
			feedbackPercent: 94.7,
			location: 'Victoria, BC',
			memberSince: '2022-06-10',
			type: 'private'
		},
		watcherCount: 17,
		saveCount: 5,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-015',
		title: '2023 Tesla Model Y Long Range AWD',
		year: 2023,
		make: 'Tesla',
		model: 'Model Y',
		trim: 'Long Range',
		price: 52_600,
		marketAverage: 55_300,
		priceBadge: 'below_market',
		mileage: 18_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Pearl White Multi-Coat',
		vin: '5YJYGDEE****1102',
		description:
			'Long Range AWD with white interior, tow hitch, and 20-inch Induction wheels. Seller includes mobile connector and notes one wheel has minor rash. App access history available. Attractive price for a fresh EV listing, but buyers will likely ask about winter range and tire wear.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Tesla_Model_Y_Front_View.jpg/960px-Tesla_Model_Y_Front_View.jpg',
			4
		),
		location: 'Calgary, AB',
		seller: {
			username: 'ryan_ev_yeg',
			feedbackScore: 203,
			feedbackPercent: 99.5,
			location: 'Calgary, AB',
			memberSince: '2015-11-04',
			type: 'private'
		},
		watcherCount: 96,
		saveCount: 63,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-016',
		title: '2014 Audi R8 V10 Coupe',
		year: 2014,
		make: 'Audi',
		model: 'R8',
		trim: 'V10',
		price: 134_900,
		marketAverage: 128_500,
		priceBadge: 'above_market',
		mileage: 27_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Suzuka Grey Metallic',
		vin: 'WUAAUAFG****0148',
		description:
			'V10 coupe with carbon side blades, magnetic ride, diamond-stitched leather, and documented annual service from Audi Richmond plus a recent clutch adaptation. Paint-protection film on the full nose and ceramic coating invoice included. This is the polished exotic listing for buyers who care about provenance, consumables, and whether the premium is justified by presentation.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Audi_R8_V10%2C_Bj._2011_%282011-08-13_322%29.JPG/960px-Audi_R8_V10%2C_Bj._2011_%282011-08-13_322%29.JPG',
			4
		),
		location: 'Richmond, BC',
		seller: {
			username: 'westline_exotics',
			feedbackScore: 622,
			feedbackPercent: 99.3,
			location: 'Richmond, BC',
			memberSince: '2011-06-21',
			type: 'dealer'
		},
		watcherCount: 126,
		saveCount: 91,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-017',
		title: '1994 Toyota Supra SZ Import 5-Speed',
		year: 1994,
		make: 'Toyota',
		model: 'Supra',
		trim: 'SZ',
		price: 46_800,
		marketAverage: 44_200,
		priceBadge: 'above_market',
		mileage: 129_600,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Super White II',
		vin: 'JZA80-00****85',
		description:
			'Right-hand-drive JDM import with naturally aspirated 2JZ, five-speed swap, TE37-style wheels, and HKS coilovers. Seller includes federal import paperwork, Japanese auction sheet translation, and photos of the underside, but service records since arriving in Canada are limited. Good example of an enthusiast car where import history, swap quality, and originality matter more than a generic price badge.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Toyota_Supra_RZ_%28JZA80%29_front.JPG/960px-Toyota_Supra_RZ_%28JZA80%29_front.JPG',
			3
		),
		location: 'Halifax, NS',
		seller: {
			username: 'maritime_jdm',
			feedbackScore: 71,
			feedbackPercent: 97.4,
			location: 'Halifax, NS',
			memberSince: '2018-01-19',
			type: 'private'
		},
		watcherCount: 109,
		saveCount: 77,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-018',
		title: '2022 Ford Bronco Outer Banks 4-Door',
		year: 2022,
		make: 'Ford',
		model: 'Bronco',
		trim: 'Outer Banks',
		price: 54_800,
		marketAverage: 51_500,
		priceBadge: 'above_market',
		mileage: 23_600,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Eruption Green Metallic',
		vin: '1FMEE5DP****4401',
		description:
			'Outer Banks with Sasquatch package, soft top, modular bumper, and Lux package. Seller says it has never been off-road and that hard-top panels are included. Premium pricing seems driven by color, options, and Bronco scarcity rather than objective value.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/2022_Ford_Bronco_4-Door_Outer_Banks_with_Sasquatch_Package%2C_front_left%2C_02-09-2023.jpg/960px-2022_Ford_Bronco_4-Door_Outer_Banks_with_Sasquatch_Package%2C_front_left%2C_02-09-2023.jpg',
			4
		),
		location: 'Vancouver, BC',
		seller: {
			username: 'west_coast_rigs',
			feedbackScore: 181,
			feedbackPercent: 99.2,
			location: 'Vancouver, BC',
			memberSince: '2014-09-05',
			type: 'private'
		},
		watcherCount: 89,
		saveCount: 58,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-019',
		title: '2004 BMW M3 Coupe 6MT',
		year: 2004,
		make: 'BMW',
		model: 'M3',
		trim: 'Coupe',
		price: 31_400,
		marketAverage: 34_700,
		priceBadge: 'below_market',
		mileage: 163_500,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Interlagos Blue Metallic',
		vin: 'WBSBL934****3380',
		description:
			'Six-speed E46 M3 with CSL-style wheels, upgraded rod bearings completed at 142k km, and a folder of receipts from a local BMW specialist. Seller is upfront that the rear subframe has not been reinforced and the rear bumper has a scrape. This sits in the middle ground between collector and track-day toy, so buyers need both maintenance confidence and chassis scrutiny.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/BMW_E46-M3.JPG/960px-BMW_E46-M3.JPG',
			2
		),
		location: 'Kitchener, ON',
		seller: {
			username: 'germanmetal_kw',
			feedbackScore: 64,
			feedbackPercent: 98.6,
			location: 'Kitchener, ON',
			memberSince: '2017-10-03',
			type: 'private'
		},
		watcherCount: 102,
		saveCount: 68,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-020',
		title: '2020 Subaru WRX Sport-tech AWD - Rebuilt Title',
		year: 2020,
		make: 'Subaru',
		model: 'WRX',
		trim: 'Sport-tech',
		price: 17_900,
		marketAverage: 27_400,
		priceBadge: 'below_market',
		mileage: 58_600,
		mileageBadge: 'average',
		condition: 'salvage',
		transmission: 'manual',
		drivetrain: 'awd',
		color: 'World Rally Blue Pearl',
		vin: 'JF1VA1E6****2205',
		description:
			'Rebuilt-title WRX from front-right collision in 2023. Seller says repairs were completed professionally and alignment is straight, but only a few repair photos are provided. Cobb intake installed, stock exhaust included. This is the intentionally suspicious value listing for AI and trust-testing flows.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Subaru_WRX_%28VA%29_front_view_%28United_States%29.jpg/960px-Subaru_WRX_%28VA%29_front_view_%28United_States%29.jpg',
			4
		),
		location: 'Surrey, BC',
		seller: {
			username: 'boostedwestcoast',
			feedbackScore: 23,
			feedbackPercent: 91.8,
			location: 'Surrey, BC',
			memberSince: '2023-05-12',
			type: 'private'
		},
		watcherCount: 112,
		saveCount: 79,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-021',
		title: '2017 Porsche Cayman S 6MT',
		year: 2017,
		make: 'Porsche',
		model: 'Cayman',
		trim: 'S',
		price: 74_500,
		marketAverage: 76_300,
		priceBadge: 'below_market',
		mileage: 39_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Guards Red',
		vin: 'WP0AB2A8****3441',
		description:
			'718 Cayman S six-speed with Sport Chrono, PASM, full leather, and recent Michelin PS4S tires. Seller includes Porsche Centre service history, paint-meter readings, and both keys. Strong enthusiast listing for buyers who care about manual cars, mid-engine balance, and clean ownership history.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/d/d8/2018_Porsche_718_Cayman_S_S-A_2.5_Front.jpg',
			4
		),
		location: 'Toronto, ON',
		seller: {
			username: 'toronto_flatsix',
			feedbackScore: 134,
			feedbackPercent: 99.2,
			location: 'Toronto, ON',
			memberSince: '2016-08-25',
			type: 'private'
		},
		watcherCount: 93,
		saveCount: 57,
		listedAt: '2026-04-05'
	},
	{
		id: 'lst-022',
		title: '2016 Chevrolet Corvette Z06 3LZ',
		year: 2016,
		make: 'Chevrolet',
		model: 'Corvette',
		trim: 'Z06 3LZ',
		price: 88_900,
		marketAverage: 86_700,
		priceBadge: 'above_market',
		mileage: 26_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Long Beach Red Metallic',
		vin: '1G1YU2D6****1942',
		description:
			'Supercharged Z06 3LZ with exposed carbon package, PDR, and recent brake fluid plus supercharger belt service. Seller claims no track days and includes stock wheels with the sale. Great high-horsepower listing for demonstrating how AI should ask about heat-soak history, tires, and consumables.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/9/95/2015_Chevrolet_Corvette_Z06_in_Velocity_Yellow%2C_Front_Right%2C_08-06-2022.jpg',
			4
		),
		location: 'Edmonton, AB',
		seller: {
			username: 'prairie_corvette',
			feedbackScore: 119,
			feedbackPercent: 98.9,
			location: 'Edmonton, AB',
			memberSince: '2015-05-07',
			type: 'private'
		},
		watcherCount: 101,
		saveCount: 69,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-023',
		title: '2001 Acura Integra Type R Clone',
		year: 2001,
		make: 'Acura',
		model: 'Integra',
		trim: 'Type R Clone',
		price: 18_600,
		marketAverage: 17_900,
		priceBadge: 'above_market',
		mileage: 198_400,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Championship White',
		vin: 'JH4DC23****7711',
		description:
			'GS-R base with B18C5 swap, seam-sealed engine bay, Recaros, and JDM front end conversion. Seller is upfront that this is not a real Type R and that some receipts are missing from the build. Useful mod-heavy scenario where provenance and swap quality matter more than the headline styling.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/8/8a/2002_Honda_Integra_%28DC5%29_Special_Edition_coupe_%282015-07-24%29_01.jpg',
			3
		),
		location: 'Ottawa, ON',
		seller: {
			username: 'dc2_parts_bin',
			feedbackScore: 47,
			feedbackPercent: 96.9,
			location: 'Ottawa, ON',
			memberSince: '2020-03-11',
			type: 'private'
		},
		watcherCount: 77,
		saveCount: 45,
		listedAt: '2026-04-05'
	},
	{
		id: 'lst-024',
		title: '1997 Land Rover Defender 90 NAS',
		year: 1997,
		make: 'Land Rover',
		model: 'Defender 90',
		trim: 'NAS',
		price: 84_200,
		marketAverage: 87_500,
		priceBadge: 'below_market',
		mileage: 142_600,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'manual',
		drivetrain: '4wd',
		color: 'Arles Blue',
		vin: 'SALDV324****1174',
		description:
			'North American Spec Defender 90 with documented frame treatment, recent clutch hydraulics, and a binder of ownership records. Seller notes minor galvanic corrosion near the cappings and an older respray. Collector-grade off-road icon where originality and rust inspection matter more than creature comforts.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/4/41/2015_Land_Rover_Defender_%28L316_MY15%29_90_3-door_wagon_%282015-10-24%29_01.jpg',
			4
		),
		location: 'Kelowna, BC',
		seller: {
			username: 'okanagan_overland',
			feedbackScore: 88,
			feedbackPercent: 98.5,
			location: 'Kelowna, BC',
			memberSince: '2017-09-18',
			type: 'private'
		},
		watcherCount: 82,
		saveCount: 53,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-025',
		title: '2021 BMW M2 Competition 6MT',
		year: 2021,
		make: 'BMW',
		model: 'M2',
		trim: 'Competition',
		price: 67_800,
		marketAverage: 69_100,
		priceBadge: 'below_market',
		mileage: 21_700,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Hockenheim Silver',
		vin: 'WBS2U7C0****5416',
		description:
			'Stock M2 Competition six-speed with carbon roof, executive package, and fresh Michelin Cup 2 Connect tires. BMW dealer service history is complete and the seller includes paint-protection film invoices. Good late-model enthusiast case where low miles and stock condition justify attention.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/b/b8/BMW_G87_M2_1X7A1838.jpg',
			4
		),
		location: 'Mississauga, ON',
		seller: {
			username: 'm2weekendcar',
			feedbackScore: 66,
			feedbackPercent: 100,
			location: 'Mississauga, ON',
			memberSince: '2019-06-09',
			type: 'private'
		},
		watcherCount: 98,
		saveCount: 62,
		listedAt: '2026-04-05'
	},
	{
		id: 'lst-026',
		title: '1991 Mazda RX-7 Turbo II Shell Project',
		year: 1991,
		make: 'Mazda',
		model: 'RX-7',
		trim: 'Turbo II',
		price: 11_400,
		marketAverage: 15_200,
		priceBadge: 'below_market',
		mileage: 180_000,
		mileageBadge: 'high',
		condition: 'fair',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Brilliant Black',
		vin: 'JM1FC351****8220',
		description:
			'FC chassis roller with engine removed, interior mostly stripped, and boxes of trim parts included. Seller says the shell is straight but the car needs paint, wiring cleanup, and a complete driveline strategy. This is a pure project-car scenario that should trigger questions about completeness, rust, and title status.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/8/8c/1994_Mazda_RX-7_R2_in_Vintage_Red%2C_front_left_%28Lime_Rock%29.jpg',
			3
		),
		location: 'Quebec City, QC',
		seller: {
			username: 'rotary_rescue_qc',
			feedbackScore: 31,
			feedbackPercent: 93.8,
			location: 'Quebec City, QC',
			memberSince: '2022-05-14',
			type: 'private'
		},
		watcherCount: 74,
		saveCount: 50,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-027',
		title: '2019 Mercedes-AMG C63 S Sedan',
		year: 2019,
		make: 'Mercedes-Benz',
		model: 'C63',
		trim: 'AMG S',
		price: 72_300,
		marketAverage: 70_200,
		priceBadge: 'above_market',
		mileage: 47_600,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'rwd',
		color: 'Selenite Grey Magno',
		vin: '55SWF8HB****6619',
		description:
			'AMG C63 S with performance seats, exhaust, night package, and ceramic coating from new. Dealer records are complete and the seller notes new rear tires plus recent brake service. Strong premium-sport-sedan example for testing whether the AI weighs presentation against a firm ask.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/5/52/Mercedes-Benz_C_200_Avantgarde_%28W_205%29_%E2%80%93_Frontansicht%2C_26._April_2014%2C_D%C3%BCsseldorf.jpg',
			4
		),
		location: 'Montreal, QC',
		seller: {
			username: 'amgmontreal',
			feedbackScore: 141,
			feedbackPercent: 99.0,
			location: 'Montreal, QC',
			memberSince: '2014-11-02',
			type: 'dealer'
		},
		watcherCount: 87,
		saveCount: 56,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-028',
		title: '1987 Buick Grand National',
		year: 1987,
		make: 'Buick',
		model: 'Grand National',
		trim: 'Turbo',
		price: 49_500,
		marketAverage: 51_700,
		priceBadge: 'below_market',
		mileage: 96_800,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'rwd',
		color: 'Black',
		vin: '1G4GJ117****6618',
		description:
			'Mostly stock Grand National with original wheels, correct intercooler plumbing, and a stack of older registration slips. Seller notes the driver seat bolster is worn and the repaint on the trunk lid has age. Nice analog muscle-car entry for buyers who care about originality and turbo V6 specifics.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/c/c4/2020_Buick_Regal_Sportback_%28United_States%29_front_view_%28cropped%29.jpg',
			3
		),
		location: 'London, ON',
		seller: {
			username: 'turbo_regal_archive',
			feedbackScore: 54,
			feedbackPercent: 98.2,
			location: 'London, ON',
			memberSince: '2018-10-28',
			type: 'private'
		},
		watcherCount: 73,
		saveCount: 40,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-029',
		title: '2020 Toyota 4Runner TRD Pro',
		year: 2020,
		make: 'Toyota',
		model: '4Runner',
		trim: 'TRD Pro',
		price: 56_900,
		marketAverage: 54_600,
		priceBadge: 'above_market',
		mileage: 61_300,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Army Green',
		vin: 'JTEBU5JR****6031',
		description:
			'TRD Pro with original Fox shocks, skid plate, roof basket, and dealer service history. Seller says it has seen mild logging-road use only and includes close photos of the frame and lower control arms. Useful overland-oriented listing where underbody condition and real usage matter.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/0/0a/2025_Toyota_4Runner_TRD_Sport_in_Wind_Chill_Pearl%2C_front_right%2C_2025-05-18.jpg',
			4
		),
		location: 'Vancouver, BC',
		seller: {
			username: 'coastal_trd',
			feedbackScore: 127,
			feedbackPercent: 99.1,
			location: 'Vancouver, BC',
			memberSince: '2016-12-17',
			type: 'private'
		},
		watcherCount: 85,
		saveCount: 47,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-030',
		title: '2018 Alfa Romeo Giulia Quadrifoglio',
		year: 2018,
		make: 'Alfa Romeo',
		model: 'Giulia',
		trim: 'Quadrifoglio',
		price: 48_700,
		marketAverage: 50_900,
		priceBadge: 'below_market',
		mileage: 58_400,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'rwd',
		color: 'Competizione Red',
		vin: 'ZARFAEAV****0917',
		description:
			'Twin-turbo Quadrifoglio with carbon roof, Sparco seats, and fresh front rotors. Seller discloses intermittent suspension warning history that was resolved after a battery replacement, but records are not complete. Good modern-performance listing where passion and maintenance anxiety collide.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/d/d9/Alfa_Romeo_Giulia_Super_%28cropped%29.jpg',
			4
		),
		location: 'Halifax, NS',
		seller: {
			username: 'eastcoast_qv',
			feedbackScore: 39,
			feedbackPercent: 97.1,
			location: 'Halifax, NS',
			memberSince: '2021-01-22',
			type: 'private'
		},
		watcherCount: 69,
		saveCount: 36,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-031',
		title: '1993 Jeep Wrangler YJ 4.0 5-Speed',
		year: 1993,
		make: 'Jeep',
		model: 'Wrangler',
		trim: 'YJ',
		price: 14_800,
		marketAverage: 16_100,
		priceBadge: 'below_market',
		mileage: 231_000,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: '4wd',
		color: 'Hunter Green Metallic',
		vin: '1J4FY29S****9932',
		description:
			'4.0 YJ with half doors, soft top, 31-inch tires, and recent rear main seal plus leaf spring bushings. Seller includes underside photos showing frame repairs near the rear shackles. Good budget off-road enthusiast entry that should trigger rust and previous trail-use questions.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/b/b9/2018_Jeep_Wrangler_Sahara_Unlimited_Multijet_2.1_Front.jpg',
			3
		),
		location: 'Fredericton, NB',
		seller: {
			username: 'maritime_yj',
			feedbackScore: 22,
			feedbackPercent: 95.4,
			location: 'Fredericton, NB',
			memberSince: '2021-10-05',
			type: 'private'
		},
		watcherCount: 42,
		saveCount: 21,
		listedAt: '2026-03-28'
	},
	{
		id: 'lst-032',
		title: '2015 Lexus RC F Coupe',
		year: 2015,
		make: 'Lexus',
		model: 'RC F',
		trim: 'Coupe',
		price: 52_900,
		marketAverage: 55_100,
		priceBadge: 'below_market',
		mileage: 67_200,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'rwd',
		color: 'Ultrasonic Blue Mica',
		vin: 'JTHHP5BC****2204',
		description:
			'Naturally aspirated V8 RC F with torque-vectoring diff, Mark Levinson audio, and full Lexus dealer history. Listing notes a replaced front lip and fresh Michelin Pilot Sport 4S tires. Strong clean-title V8 enthusiast listing with reliability appeal compared with more temperamental rivals.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/7/7f/2018_Lexus_RC_300h_F_Sport_LSS%2B_CVT_2.5.jpg',
			4
		),
		location: 'Calgary, AB',
		seller: {
			username: 'yyc_v8_coupe',
			feedbackScore: 73,
			feedbackPercent: 99.4,
			location: 'Calgary, AB',
			memberSince: '2018-06-03',
			type: 'private'
		},
		watcherCount: 71,
		saveCount: 39,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-033',
		title: '1986 Chevrolet K10 Scottsdale Restomod',
		year: 1986,
		make: 'Chevrolet',
		model: 'K10',
		trim: 'Scottsdale',
		price: 38_400,
		marketAverage: 40_600,
		priceBadge: 'below_market',
		mileage: 112_000,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Dark Blue Metallic',
		vin: '1GCEK14H****2013',
		description:
			'Square-body K10 with crate 350, Holley Sniper EFI, new interior, and mild suspension lift. Seller says the build is complete but some gauges are not wired correctly and the paint has a few fisheyes. Good restomod listing where build quality matters as much as the parts list.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/3/39/1986_GMC_Sierra_Classic_3%2B3_Pick-Up_%2817473647306%29_%28cropped%29.jpg',
			3
		),
		location: 'Saskatoon, SK',
		seller: {
			username: 'squarebody_prairie',
			feedbackScore: 45,
			feedbackPercent: 97.8,
			location: 'Saskatoon, SK',
			memberSince: '2019-04-26',
			type: 'private'
		},
		watcherCount: 57,
		saveCount: 29,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-034',
		title: '2022 Cadillac CT5-V Blackwing 6MT',
		year: 2022,
		make: 'Cadillac',
		model: 'CT5-V Blackwing',
		trim: 'Base',
		price: 109_800,
		marketAverage: 112_400,
		priceBadge: 'below_market',
		mileage: 14_900,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Electric Blue',
		vin: '1G6D25RP****1405',
		description:
			'Six-speed Blackwing with bronze wheel package, front PPF, and complete Cadillac dealer records. Seller says the car attended one track-day school with fresh fluid service immediately after. High-end enthusiast case where honesty about limited track use can still be acceptable if maintenance is strong.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/2/28/2024_Cadillac_CT5-V_AWD%2C_front_12.20.24.jpg',
			4
		),
		location: 'Winnipeg, MB',
		seller: {
			username: 'blackwingweekend',
			feedbackScore: 33,
			feedbackPercent: 100,
			location: 'Winnipeg, MB',
			memberSince: '2022-02-13',
			type: 'private'
		},
		watcherCount: 90,
		saveCount: 58,
		listedAt: '2026-04-05'
	},
	{
		id: 'lst-035',
		title: '2008 Subaru Forester XT Sport 5MT',
		year: 2008,
		make: 'Subaru',
		model: 'Forester',
		trim: 'XT Sport',
		price: 13_900,
		marketAverage: 14_800,
		priceBadge: 'below_market',
		mileage: 176_800,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'awd',
		color: 'Spark Silver Metallic',
		vin: 'JF1SG696****4138',
		description:
			'Turbo manual Forester with VF52 upgrade, STI pink springs, and stack of tuning receipts from 2022 onward. Seller says the head gaskets were done before the turbo swap and includes a conservative dyno sheet. Good used enthusiast wagon example where mod quality and engine health matter more than cosmetics.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/4/48/Subaru_Forester_%28SL%29_e-BOXER_DSC_8811.jpg',
			4
		),
		location: 'Kingston, ON',
		seller: {
			username: 'boostedwagon613',
			feedbackScore: 52,
			feedbackPercent: 96.8,
			location: 'Kingston, ON',
			memberSince: '2019-07-07',
			type: 'private'
		},
		watcherCount: 68,
		saveCount: 37,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-036',
		title: '1972 Datsun 240Z Restoration Candidate',
		year: 1972,
		make: 'Datsun',
		model: '240Z',
		trim: 'Coupe',
		price: 24_200,
		marketAverage: 28_700,
		priceBadge: 'below_market',
		mileage: 87_000,
		mileageBadge: 'average',
		condition: 'fair',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Orange',
		vin: 'HLS30-6****12',
		description:
			'Matching-numbers L24 car that has been off the road since 2011. Seller says the engine turns by hand, hatch floor needs repair, and the interior is partially disassembled but mostly present. Ideal vintage Japanese project listing for testing completeness, rust, and authenticity questions.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/6/64/1970-1973_Nissan_Fairlady_Z.jpg',
			3
		),
		location: 'Victoria, BC',
		seller: {
			username: 'island_zcars',
			feedbackScore: 27,
			feedbackPercent: 94.9,
			location: 'Victoria, BC',
			memberSince: '2021-04-02',
			type: 'private'
		},
		watcherCount: 79,
		saveCount: 54,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-037',
		title: '2011 Mitsubishi Lancer Evolution MR',
		year: 2011,
		make: 'Mitsubishi',
		model: 'Lancer Evolution',
		trim: 'MR',
		price: 31_700,
		marketAverage: 33_200,
		priceBadge: 'below_market',
		mileage: 118_300,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Phantom Black Pearl',
		vin: 'JA32W8FV****5517',
		description:
			'SST Evo MR with intake, downpipe, and recent transfer case service. Seller provides compression results and a tune sheet but says the car has seen occasional autocross events. Strong case for AI to ask about SST maintenance, hard use, and whether emissions equipment is still present.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/9/91/2017-04-02_Mitsubishi_Lancer_Evolution_X_MR_SST_14_%282%29.jpg',
			4
		),
		location: 'Surrey, BC',
		seller: {
			username: 'evoxlowermainland',
			feedbackScore: 43,
			feedbackPercent: 95.9,
			location: 'Surrey, BC',
			memberSince: '2020-08-12',
			type: 'private'
		},
		watcherCount: 83,
		saveCount: 52,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-038',
		title: '2010 Ford F-150 SVT Raptor SuperCab',
		year: 2010,
		make: 'Ford',
		model: 'F-150',
		trim: 'SVT Raptor',
		price: 29_800,
		marketAverage: 31_000,
		priceBadge: 'below_market',
		mileage: 171_400,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Ingot Silver Metallic',
		vin: '1FTEX1EV****8247',
		description:
			'6.2 Raptor with Fox shocks refreshed in 2024, method wheels, and light cosmetic trail rash on the bedside. Seller says it has done desert trips in the US and includes recent transmission service invoice. Good off-road performance scenario where hard use does not automatically kill the deal, but must be priced in.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/e/ee/Ford_F-150_SVT_Raptor_2011_%2815245966030%29.jpg',
			4
		),
		location: 'Calgary, AB',
		seller: {
			username: 'raptoryyc',
			feedbackScore: 61,
			feedbackPercent: 97.5,
			location: 'Calgary, AB',
			memberSince: '2018-02-18',
			type: 'private'
		},
		watcherCount: 64,
		saveCount: 31,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-039',
		title: '2023 Lotus Emira First Edition',
		year: 2023,
		make: 'Lotus',
		model: 'Emira',
		trim: 'First Edition',
		price: 121_500,
		marketAverage: 124_900,
		priceBadge: 'below_market',
		mileage: 6_400,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'rwd',
		color: 'Seneca Blue',
		vin: 'SCCLEKAX****0197',
		description:
			'V6 manual Emira with touring suspension, full PPF, and dealer break-in service completed on time. Seller says the car has only been used for weekend drives and includes delivery paperwork plus window sticker. Modern exotic listing that should surface originality, warranty transfer, and low-volume ownership questions.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/a/aa/2024_Lotus_Emira_First_Edition_3.jpg',
			4
		),
		location: 'Toronto, ON',
		seller: {
			username: 'lotusfirstedition',
			feedbackScore: 24,
			feedbackPercent: 100,
			location: 'Toronto, ON',
			memberSince: '2023-03-29',
			type: 'private'
		},
		watcherCount: 95,
		saveCount: 63,
		listedAt: '2026-04-05'
	},
	{
		id: 'lst-040',
		title: '1988 Honda CRX Si Track Build',
		year: 1988,
		make: 'Honda',
		model: 'CRX',
		trim: 'Si',
		price: 12_900,
		marketAverage: 14_300,
		priceBadge: 'below_market',
		mileage: 249_000,
		mileageBadge: 'high',
		condition: 'fair',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Rio Red',
		vin: 'JHMEC134****5102',
		description:
			'Caged CRX Si with B16 swap, stripped interior, and logbook from local time-attack events. Seller admits it is no longer street comfortable and the windshield is cracked, but the shell looks straight in photos. This is the edge-case track-build scenario where the AI should ask whether the buyer wants a toy or a headache.',
		photos: repeatPhoto(
			'https://upload.wikimedia.org/wikipedia/commons/2/20/Honda_CR-X_1987.jpg',
			3
		),
		location: 'Hamilton, ON',
		seller: {
			username: 'hamiltonhondaoldschool',
			feedbackScore: 36,
			feedbackPercent: 94.4,
			location: 'Hamilton, ON',
			memberSince: '2021-09-01',
			type: 'private'
		},
		watcherCount: 70,
		saveCount: 44,
		listedAt: '2026-04-04'
	}
];
