import type { Listing } from '$lib/types/listing';

// Deterministic placeholder images so cards stay visually stable across reloads.
const img = (id: number, w = 960, h = 640) => `https://picsum.photos/seed/vehicle-${id}/${w}/${h}`;

export const mockListings: Listing[] = [
	{
		id: 'lst-001',
		title: '2019 Honda CR-V EX-L AWD',
		year: 2019,
		make: 'Honda',
		model: 'CR-V',
		trim: 'EX-L',
		price: 22_900,
		marketAverage: 24_700,
		priceBadge: 'below_market',
		mileage: 46_800,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Lunar Silver Metallic',
		vin: '2HKRW2H8****4521',
		description:
			'One-owner family SUV with Honda dealer records from new. EX-L trim with leather, heated seats, power tailgate, sunroof, and Apple CarPlay. Recent work includes rear brakes, battery, and the 48k service. No accident claims reported. Includes winter wheels and cargo tray.',
		photos: [img(1), img(2), img(3), img(4)],
		location: 'Toronto, ON',
		seller: {
			username: 'PaulaT_Drives',
			feedbackScore: 318,
			feedbackPercent: 99.4,
			location: 'Toronto, ON',
			memberSince: '2014-03-11',
			type: 'private'
		},
		watcherCount: 52,
		saveCount: 27,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-002',
		title: '2021 Toyota RAV4 XLE Premium AWD',
		year: 2021,
		make: 'Toyota',
		model: 'RAV4',
		trim: 'XLE Premium',
		price: 31_800,
		marketAverage: 30_900,
		priceBadge: 'above_market',
		mileage: 29_400,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Blueprint',
		vin: '2T3P1RFV****8802',
		description:
			'Toyota Certified with balance of powertrain warranty and a fresh 160-point inspection. XLE Premium with SofTex, power liftgate, sunroof, blind-spot monitoring, and all-weather liners. Dealer asking a premium because it is clean, local, and fully reconditioned.',
		photos: [img(5), img(6), img(7), img(8)],
		location: 'Mississauga, ON',
		seller: {
			username: 'OakvilleToyota_Official',
			feedbackScore: 2841,
			feedbackPercent: 98.7,
			location: 'Mississauga, ON',
			memberSince: '2009-06-02',
			type: 'dealer'
		},
		watcherCount: 64,
		saveCount: 35,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-003',
		title: '2017 Ford F-150 XLT SuperCrew 4x4',
		year: 2017,
		make: 'Ford',
		model: 'F-150',
		trim: 'XLT',
		price: 24_600,
		marketAverage: 24_100,
		priceBadge: 'fair',
		mileage: 89_700,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Oxford White',
		vin: '1FTFW1EF****3317',
		description:
			'3.5L EcoBoost, SuperCrew, tow package, spray-in liner. Used for commuting and weekend hardware-store runs, not heavy towing. Service history is complete to 2022, then maintained at a local independent shop. Tailgate and rear bumper have light scratches shown in photos.',
		photos: [img(9), img(10), img(11), img(12)],
		location: 'Calgary, AB',
		seller: {
			username: 'mike_alberta',
			feedbackScore: 91,
			feedbackPercent: 97.8,
			location: 'Calgary, AB',
			memberSince: '2017-08-14',
			type: 'private'
		},
		watcherCount: 37,
		saveCount: 15,
		listedAt: '2026-03-28'
	},
	{
		id: 'lst-004',
		title: '2022 Mazda CX-5 GT AWD',
		year: 2022,
		make: 'Mazda',
		model: 'CX-5',
		trim: 'GT',
		price: 33_400,
		marketAverage: 35_000,
		priceBadge: 'below_market',
		mileage: 22_100,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Soul Red Crystal',
		vin: 'JM3KFBDM****5573',
		description:
			'Former executive fleet vehicle with complete Mazda dealer history and recent inspection. GT trim includes Bose audio, HUD, heated and ventilated front seats, heated rear seats, adaptive cruise, and power tailgate. Very clean interior, no smoke smell, no visible wear on bolsters.',
		photos: [img(13), img(14), img(15), img(16), img(17)],
		location: 'Vancouver, BC',
		seller: {
			username: 'PacificFleetSales',
			feedbackScore: 1204,
			feedbackPercent: 99.1,
			location: 'Vancouver, BC',
			memberSince: '2011-01-20',
			type: 'dealer'
		},
		watcherCount: 73,
		saveCount: 46,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-005',
		title: '2015 Toyota Camry XSE V6',
		year: 2015,
		make: 'Toyota',
		model: 'Camry',
		trim: 'XSE V6',
		price: 13_100,
		marketAverage: 14_900,
		priceBadge: 'below_market',
		mileage: 121_400,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'fwd',
		color: 'Midnight Black Metallic',
		vin: '4T1BK1FK****6605',
		description:
			'High-mileage V6 Camry that still drives strong. Two keys, remote start, and recent front struts. Seller says there is no rust through, only stone chips and a crack in the lower front lip. Description is brief, so a buyer should confirm oil-consumption history and transmission service.',
		photos: [img(18), img(19), img(20)],
		location: 'Ottawa, ON',
		seller: {
			username: 'dave_ottawa99',
			feedbackScore: 44,
			feedbackPercent: 96.2,
			location: 'Ottawa, ON',
			memberSince: '2019-11-30',
			type: 'private'
		},
		watcherCount: 24,
		saveCount: 10,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-006',
		title: '2020 Volkswagen Golf GTI Autobahn 6MT',
		year: 2020,
		make: 'Volkswagen',
		model: 'Golf GTI',
		trim: 'Autobahn',
		price: 28_100,
		marketAverage: 26_800,
		priceBadge: 'above_market',
		mileage: 34_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Tornado Red',
		vin: '3VW547AUXLM****42',
		description:
			'Manual Autobahn with DCC, Fender audio, navigation, and plaid-seat delete. Seller states the car was never tracked and remains stock aside from Michelin Pilot Sport tires. Dealer reconditioning included fresh front brakes and a carbon cleaning service. Strong enthusiast appeal, but priced above average.',
		photos: [img(21), img(22), img(23), img(24)],
		location: 'Oakville, ON',
		seller: {
			username: 'PrestigeAutoHaus',
			feedbackScore: 743,
			feedbackPercent: 98.9,
			location: 'Oakville, ON',
			memberSince: '2013-05-17',
			type: 'dealer'
		},
		watcherCount: 59,
		saveCount: 30,
		listedAt: '2026-03-29'
	},
	{
		id: 'lst-007',
		title: '2016 Honda Civic LX Sedan',
		year: 2016,
		make: 'Honda',
		model: 'Civic',
		trim: 'LX',
		price: 9_200,
		marketAverage: 10_300,
		priceBadge: 'below_market',
		mileage: 136_900,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Taffeta White',
		vin: '2HGFC2F5****7801',
		description: 'Reliable commuter. Good on gas. Two sets of tires. Selling as-is.',
		photos: [img(25), img(26)],
		location: 'Hamilton, ON',
		seller: {
			username: 'sam_h_sells',
			feedbackScore: 28,
			feedbackPercent: 100,
			location: 'Hamilton, ON',
			memberSince: '2021-02-08',
			type: 'private'
		},
		watcherCount: 21,
		saveCount: 8,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-008',
		title: '2023 Subaru Outback Touring XT',
		year: 2023,
		make: 'Subaru',
		model: 'Outback',
		trim: 'Touring XT',
		price: 41_200,
		marketAverage: 42_900,
		priceBadge: 'below_market',
		mileage: 12_600,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'cvt',
		drivetrain: 'awd',
		color: 'Autumn Green Metallic',
		vin: '4S4BTAPC****3302',
		description:
			'Turbo Touring XT lease return with the full Subaru Eyesight suite, Nappa leather, heated wheel, ventilated seats, front camera, and factory hitch. Dealer notes a clean inspection and original paint on all panels. Strong fit for family-road-trip and winter-weather searches.',
		photos: [img(27), img(28), img(29), img(30)],
		location: 'Edmonton, AB',
		seller: {
			username: 'NorthStarSubaru',
			feedbackScore: 1893,
			feedbackPercent: 99.3,
			location: 'Edmonton, AB',
			memberSince: '2008-09-14',
			type: 'dealer'
		},
		watcherCount: 86,
		saveCount: 54,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-009',
		title: '2018 BMW 330i xDrive',
		year: 2018,
		make: 'BMW',
		model: '3 Series',
		trim: '330i xDrive',
		price: 26_300,
		marketAverage: 28_600,
		priceBadge: 'below_market',
		mileage: 71_500,
		mileageBadge: 'average',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Melbourne Red Metallic',
		vin: 'WBA8B9C5****2261',
		description:
			'Sport Line with black interior, heated seats, and HUD. Seller discloses curb rash on one wheel and says the valve cover gasket was done last year. Service records are partial rather than complete. Looks attractive on price, but maintenance questions will matter here.',
		photos: [img(31), img(32), img(33), img(34)],
		location: 'Toronto, ON',
		seller: {
			username: 'euro_drives_toronto',
			feedbackScore: 156,
			feedbackPercent: 98.1,
			location: 'Toronto, ON',
			memberSince: '2016-07-22',
			type: 'private'
		},
		watcherCount: 41,
		saveCount: 18,
		listedAt: '2026-03-31'
	},
	{
		id: 'lst-010',
		title: '2014 Chevrolet Silverado 1500 LTZ 4x4',
		year: 2014,
		make: 'Chevrolet',
		model: 'Silverado 1500',
		trim: 'LTZ',
		price: 18_500,
		marketAverage: 18_100,
		priceBadge: 'fair',
		mileage: 159_300,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Tungsten Metallic',
		vin: '1GCVKREC****4432',
		description:
			'Z71 package, crew cab, 5.3 V8. Seller says the transmission was replaced at 140k and provides a receipt. Some surface rust on the frame and lower bed sides, typical for prairie use. Practical truck listing with enough detail to be believable, but not especially polished.',
		photos: [img(35), img(36), img(37)],
		location: 'Saskatoon, SK',
		seller: {
			username: 'prairie_worktrucks',
			feedbackScore: 67,
			feedbackPercent: 97.0,
			location: 'Saskatoon, SK',
			memberSince: '2018-04-03',
			type: 'private'
		},
		watcherCount: 30,
		saveCount: 13,
		listedAt: '2026-03-26'
	},
	{
		id: 'lst-011',
		title: '2021 Hyundai Tucson Preferred AWD',
		year: 2021,
		make: 'Hyundai',
		model: 'Tucson',
		trim: 'Preferred',
		price: 24_700,
		marketAverage: 25_800,
		priceBadge: 'below_market',
		mileage: 40_500,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Phantom Black',
		vin: 'KM8J2CA4****9012',
		description:
			'One-owner Tucson with heated seats, heated wheel, lane keep assist, blind-spot monitoring, and remote start. Seller is moving overseas and wants a quick sale but still has dealer maintenance invoices. Good example of a realistic private listing that is clean, credible, and slightly under market.',
		photos: [img(38), img(39), img(40), img(41)],
		location: 'Montreal, QC',
		seller: {
			username: 'leila_mtl',
			feedbackScore: 74,
			feedbackPercent: 100,
			location: 'Montreal, QC',
			memberSince: '2020-01-15',
			type: 'private'
		},
		watcherCount: 55,
		saveCount: 30,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-012',
		title: '2019 Audi Q5 Progressiv Quattro',
		year: 2019,
		make: 'Audi',
		model: 'Q5',
		trim: 'Progressiv',
		price: 34_900,
		marketAverage: 33_100,
		priceBadge: 'above_market',
		mileage: 54_100,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Florett Silver Metallic',
		vin: 'WA1BNAFY****3344',
		description:
			'Progressiv trim with Virtual Cockpit, pano roof, 360 camera, and Bang & Olufsen audio. Audi dealer has full records and notes fresh tires plus front brakes. Price is on the high side, but the listing quality and reconditioning are unusually strong compared with private-market examples.',
		photos: [img(42), img(43), img(44), img(45)],
		location: 'Ottawa, ON',
		seller: {
			username: 'AudiCentreOttawa',
			feedbackScore: 3102,
			feedbackPercent: 99.0,
			location: 'Ottawa, ON',
			memberSince: '2007-03-12',
			type: 'dealer'
		},
		watcherCount: 66,
		saveCount: 34,
		listedAt: '2026-03-30'
	},
	{
		id: 'lst-013',
		title: '2020 Kia Telluride EX AWD',
		year: 2020,
		make: 'Kia',
		model: 'Telluride',
		trim: 'EX',
		price: 35_600,
		marketAverage: 36_100,
		priceBadge: 'fair',
		mileage: 46_200,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Snow White Pearl',
		vin: '5XYP3DHC****1177',
		description:
			'EX AWD with captain chairs, dual sunroofs, Harman Kardon audio, and full Kia service history. Clean family-hauler listing with enough equipment to explain shopper interest. Dealer notes one previous windshield replacement but no collision repair.',
		photos: [img(46), img(47), img(48), img(49)],
		location: 'Winnipeg, MB',
		seller: {
			username: 'KiaCityWinnipeg',
			feedbackScore: 988,
			feedbackPercent: 98.5,
			location: 'Winnipeg, MB',
			memberSince: '2010-08-22',
			type: 'dealer'
		},
		watcherCount: 78,
		saveCount: 43,
		listedAt: '2026-04-01'
	},
	{
		id: 'lst-014',
		title: '2012 Toyota Prius Three',
		year: 2012,
		make: 'Toyota',
		model: 'Prius',
		trim: 'Three',
		price: 7_800,
		marketAverage: 9_000,
		priceBadge: 'below_market',
		mileage: 191_600,
		mileageBadge: 'high',
		condition: 'fair',
		transmission: 'cvt',
		drivetrain: 'fwd',
		color: 'Classic Silver Metallic',
		vin: 'JTDKN3DU****8811',
		description:
			'High-mileage commuter with cosmetic wear, a cracked rear bumper corner, and fading on the roof. Seller says the hybrid battery is original and the car still returns strong fuel economy. This is intentionally a riskier budget listing that should trigger battery-health and maintenance questions.',
		photos: [img(50), img(51), img(52)],
		location: 'Victoria, BC',
		seller: {
			username: 'vic_green_cars',
			feedbackScore: 19,
			feedbackPercent: 94.7,
			location: 'Victoria, BC',
			memberSince: '2022-06-10',
			type: 'private'
		},
		watcherCount: 17,
		saveCount: 5,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-015',
		title: '2023 Tesla Model Y Long Range AWD',
		year: 2023,
		make: 'Tesla',
		model: 'Model Y',
		trim: 'Long Range',
		price: 52_600,
		marketAverage: 55_300,
		priceBadge: 'below_market',
		mileage: 18_200,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: 'awd',
		color: 'Pearl White Multi-Coat',
		vin: '5YJYGDEE****1102',
		description:
			'Long Range AWD with white interior, tow hitch, and 20-inch Induction wheels. Seller includes mobile connector and notes one wheel has minor rash. App access history available. Attractive price for a fresh EV listing, but buyers will likely ask about winter range and tire wear.',
		photos: [img(53), img(54), img(55), img(56)],
		location: 'Calgary, AB',
		seller: {
			username: 'ryan_ev_yeg',
			feedbackScore: 203,
			feedbackPercent: 99.5,
			location: 'Calgary, AB',
			memberSince: '2015-11-04',
			type: 'private'
		},
		watcherCount: 96,
		saveCount: 63,
		listedAt: '2026-04-03'
	},
	{
		id: 'lst-016',
		title: '2018 Ram 1500 Laramie Crew Cab 4x4',
		year: 2018,
		make: 'Ram',
		model: '1500',
		trim: 'Laramie',
		price: 36_700,
		marketAverage: 34_000,
		priceBadge: 'above_market',
		mileage: 72_800,
		mileageBadge: 'average',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Bright Silver Metallic',
		vin: '1C6RR7NT****5522',
		description:
			'Laramie with air suspension, heated and cooled leather, RamBox, panoramic roof, and upgraded audio. Dealer is asking strong money because the truck is stock, clean underneath, and fully serviced. Good case for testing when a nice listing is still likely overpriced.',
		photos: [img(57), img(58), img(59), img(60)],
		location: 'London, ON',
		seller: {
			username: 'StarlightAutoLondon',
			feedbackScore: 512,
			feedbackPercent: 97.8,
			location: 'London, ON',
			memberSince: '2012-02-14',
			type: 'dealer'
		},
		watcherCount: 48,
		saveCount: 22,
		listedAt: '2026-03-29'
	},
	{
		id: 'lst-017',
		title: '2016 Jeep Cherokee Trailhawk 4x4',
		year: 2016,
		make: 'Jeep',
		model: 'Cherokee',
		trim: 'Trailhawk',
		price: 15_600,
		marketAverage: 15_500,
		priceBadge: 'fair',
		mileage: 106_700,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Hydro Blue Pearl',
		vin: '1C4PJMBS****7733',
		description:
			'Trailhawk with skid plates, tow hooks, and Selec-Terrain. Seller mentions the 9-speed transmission was reprogrammed after a dealer visit and that the battery is new. Good trail-focused spec, but the drivetrain history is exactly the kind of detail buyers should press on.',
		photos: [img(61), img(62), img(63)],
		location: 'Halifax, NS',
		seller: {
			username: 'jason_ns_offroad',
			feedbackScore: 52,
			feedbackPercent: 98.1,
			location: 'Halifax, NS',
			memberSince: '2019-03-28',
			type: 'private'
		},
		watcherCount: 28,
		saveCount: 11,
		listedAt: '2026-03-31'
	},
	{
		id: 'lst-018',
		title: '2022 Ford Bronco Outer Banks 4-Door',
		year: 2022,
		make: 'Ford',
		model: 'Bronco',
		trim: 'Outer Banks',
		price: 54_800,
		marketAverage: 51_500,
		priceBadge: 'above_market',
		mileage: 23_600,
		mileageBadge: 'low',
		condition: 'excellent',
		transmission: 'automatic',
		drivetrain: '4wd',
		color: 'Eruption Green Metallic',
		vin: '1FMEE5DP****4401',
		description:
			'Outer Banks with Sasquatch package, soft top, modular bumper, and Lux package. Seller says it has never been off-road and that hard-top panels are included. Premium pricing seems driven by color, options, and Bronco scarcity rather than objective value.',
		photos: [img(64), img(65), img(66), img(67)],
		location: 'Vancouver, BC',
		seller: {
			username: 'west_coast_rigs',
			feedbackScore: 181,
			feedbackPercent: 99.2,
			location: 'Vancouver, BC',
			memberSince: '2014-09-05',
			type: 'private'
		},
		watcherCount: 89,
		saveCount: 58,
		listedAt: '2026-04-04'
	},
	{
		id: 'lst-019',
		title: '2013 Honda Accord Sport 6MT',
		year: 2013,
		make: 'Honda',
		model: 'Accord',
		trim: 'Sport',
		price: 8_100,
		marketAverage: 9_800,
		priceBadge: 'below_market',
		mileage: 147_900,
		mileageBadge: 'high',
		condition: 'good',
		transmission: 'manual',
		drivetrain: 'fwd',
		color: 'Alabaster Silver Metallic',
		vin: '1HGCR2F5****9941',
		description: 'Manual Accord. Clean title. Clutch feels good. Minor rust starting on rear arch.',
		photos: [img(68), img(69)],
		location: 'Kitchener, ON',
		seller: {
			username: 'kitchener_cars',
			feedbackScore: 37,
			feedbackPercent: 97.3,
			location: 'Kitchener, ON',
			memberSince: '2020-07-19',
			type: 'private'
		},
		watcherCount: 18,
		saveCount: 7,
		listedAt: '2026-04-02'
	},
	{
		id: 'lst-020',
		title: '2020 Subaru WRX Sport-tech AWD - Rebuilt Title',
		year: 2020,
		make: 'Subaru',
		model: 'WRX',
		trim: 'Sport-tech',
		price: 17_900,
		marketAverage: 27_400,
		priceBadge: 'below_market',
		mileage: 58_600,
		mileageBadge: 'average',
		condition: 'salvage',
		transmission: 'manual',
		drivetrain: 'awd',
		color: 'World Rally Blue Pearl',
		vin: 'JF1VA1E6****2205',
		description:
			'Rebuilt-title WRX from front-right collision in 2023. Seller says repairs were completed professionally and alignment is straight, but only a few repair photos are provided. Cobb intake installed, stock exhaust included. This is the intentionally suspicious value listing for AI and trust-testing flows.',
		photos: [img(70), img(71), img(72), img(73)],
		location: 'Surrey, BC',
		seller: {
			username: 'boostedwestcoast',
			feedbackScore: 23,
			feedbackPercent: 91.8,
			location: 'Surrey, BC',
			memberSince: '2023-05-12',
			type: 'private'
		},
		watcherCount: 112,
		saveCount: 79,
		listedAt: '2026-04-04'
	}
];
